#PythonMHD_Constants.py
#By Delica Leboe-McGowan, PhD Student, University of Manitoba
#Last Updated: January 1, 2024
#Purpose: Defines all constants (i.e., parameter strings and default values) that are used in PythonMHD.

#NUMERICAL CONSTANTS
SMALL_VALUE = 0.000000000001
FOUR_THIRDS = 1.333333333333333

#BOUNDARY CONDITION CONSTANTS
OUTFLOW = 0
PERIODIC = 1

#COORDINATE SYSTEM CONSTANTS
CARTESIAN = "Cartesian"
CYLINDRICAL = "Cylindrical"
SPHERICAL = "Spherical"

#GRID CONSTANTS
GRID_TYPE = "gridType"
NUM_X_CELLS = "numXCells"
MIN_X = "minX"
MAX_X = "maxX"
BC_X = "BcX"
NUM_Y_CELLS = "numYCells"
MIN_Y = "minY"
MAX_Y = "maxY"
BC_Y = "BcY"
NUM_Z_CELLS = "numZCells"
MIN_Z = "minZ"
MAX_Z = "maxZ"
BC_Z = "BcZ"
DEFAULT_BC_X = OUTFLOW
DEFAULT_BC_Y = OUTFLOW
DEFAULT_BC_Z = OUTFLOW


#SIMULATION CONSTANTS
DEFAULT_IS_MHD = False
DEFAULT_MIN_DENSITY = 0.000000000001
DEFAULT_MIN_PRESSURE = 0.000000000001
DEFAULT_MIN_ENERGY = 0.000000000001
DEFAULT_CFL_1D = 0.8
DEFAULT_CFL_2D = 0.8
DEFAULT_CFL_3D = 0.4
DEFAULT_MAX_CYCLES = 50000
DEFAULT_GAMMA = 1.4
DEFAULT_EPSILON = 0.5
IS_MHD = "isMHD"
TLIM = "tLim"
MAX_CYCLES = "maxCycles"
GAMMA = "gamma"
CFL = "cfl"
MIN_DENSITY = "minDens"
MIN_PRESSURE = "minPres"
MIN_ENERGY = "minEnergy"
RECONSTRUCT_ORDER = "reconstructOrder"
RIEMANN_SOLVER = "riemannSolver"
ENTROPY_FIX = "entropyFix"
EPSILON = "epsilon"
PLOT_DATA = "plotData"
PLOT_DATA_DT = "plotDt"
SAVE_FIGS = "saveFigs"
SAVE_FIGS_FORMAT = "figFormat"
MAKE_MOVIE = "makeMovie"
SAVE_DATA = "saveData"
SAVE_DATA_DT = "saveDt"
SAVE_DATA_FORMAT = "dataFormat"
OUTPUT_FOLDER_PATH = "outputFolderPath"
OUTPUT_FOLDER_NAME = "outputFolderName"
OUTPUT_FILE_NAME = "outputFileName"
PRIMITIVE = "primitive"
CONSERVATIVE = "conservative"

#RECONSTRUCTION CONSTANTS
NO_SPATIAL_RECONSTRUCTION = 0
#PLM_SPATIAL_RECONSTRUCTION = 1
PPM_SPATIAL_RECONSTRUCTION = 2
DEFAULT_SPATIAL_RECONSTRUCTION = PPM_SPATIAL_RECONSTRUCTION

#ANALYSIS CONSTANTS
MAX_ERROR_CELLS_TO_PRINT = 10
MAX_INDICES_TO_PRINT = 10

#VARIABLE CONSTANTS
DENSITY = "Density"
VX = "Vx"
VY = "Vy"
VZ = "Vz"
V = "V"
V2 = "V2"
PRESSURE = "Pressure"
ENERGY = "Energy"
HYDRO_PLOT_VARS = [DENSITY,
                   VX,
                   VY,
                   VZ,
                   V,
                   V2,
                   PRESSURE,
                   ENERGY]
BX = "Bx"
BY = "By"
BZ = "Bz"
B = "B"
B2 = "B^2"
TOTAL_PRESSURE = "Total Pressure"
MHD_PLOT_VARS = [DENSITY,
                 VX,
                 VY,
                 VZ,
                 V,
                 V2,
                 BX,
                 BY,
                 BZ,
                 B,
                 B2,
                 PRESSURE,
                 TOTAL_PRESSURE,
                 ENERGY]

#VISUALIZATION CONSTANTS
DEFAULT_PLOT_DATA = False
MAX_PLOTS = 9
MAX_PLOT_BREAKS = 200
DEFAULT_FRAME_RATE = 10
SIM_VISUALIZER_SMALL_DIFF_VALUE = 0.000000000001
DEFAULT_PLOT_VAR = DENSITY
PLOT_TYPE_1D = "1DPlot"
PLOT_TYPE_2D = "2DPlot"
PLOT_TYPE_3D = "3DPlot"
VALID_PLOT_TYPES = [PLOT_TYPE_1D, PLOT_TYPE_2D, PLOT_TYPE_3D]
X_AXIS = "x"
Y_AXIS = "y"
Z_AXIS = "z"
VALID_2D_AXES = ["x","y"]
VALID_3D_AXES = ["x","y","z"]
XY_PLANE = "xy"
XZ_PLANE = "xz"
YZ_PLANE = "yz"
VALID_3D_PLANES = ["xy","xz","yz"]
X_POS = "xPos"
Y_POS = "yPos"
Z_POS = "zPos"
DEFAULT_PLOT_COLOR_1D = "b"
DEFAULT_COLORMAP_2D = "viridis"
DEFAULT_COLORMAP_3D = "Blues"
DEFAULT_PLOT_ALPHA = 0.005
MINIMUM_COLORMAP_DIFFERENCE = 0.00000001
DEFAULT_MAKE_MOVIE = False
MATPLOTLIB_BACKEND = "matplotlibBackend"
MATPLOTLIB_BACKEND_TKAGG = "TkAgg"
MATPLOTLIB_BACKEND_QT4AGG = "Qt4Agg"
MATPLOTLIB_BACKEND_GTK3AGG = "GTK3Agg"
MATPLOTLIB_BACKEND_MACOSX = "macosx"
MATPLOTLIB_BACKEND_NBAGG = "nbAgg"
MATPLOTLIB_BACKEND_WEBAGG = "WebAgg"
MATPLOTLIB_BACKEND_GTK3Cairo = "GTK3Cairo"
MATPLOTLIB_BACKEND_WXAGG = "wxAgg"
DEFAULT_MATPLOTLIB_BACKEND = MATPLOTLIB_BACKEND_TKAGG
MATPLOTLIB_INTERACTIVE_BACKENDS = [MATPLOTLIB_BACKEND_TKAGG,MATPLOTLIB_BACKEND_QT4AGG,
                                   MATPLOTLIB_BACKEND_GTK3AGG, MATPLOTLIB_BACKEND_MACOSX,
                                   MATPLOTLIB_BACKEND_NBAGG, MATPLOTLIB_BACKEND_WEBAGG, MATPLOTLIB_BACKEND_GTK3Cairo,
                                   MATPLOTLIB_BACKEND_WXAGG]
MAX_PLOT_TITLE_TIME_PREC = 10
MAX_PLOT_TITLE_POSITION_PREC = 10
FIGURES = "figures"
FIGURE = "figure"
FIGURE_TITLE = "figureTitle"
FIGURE_OUTPUT_FORMAT = "figureOutputFormat"
FIGURE_DPI = "figureDPI"
PLOTS = "plots"
COLORBARS = "colorbars"
USETK = "useTk"
AXES = "axes"
NUM_PLOTS = "numPlots"
PLOT_VAR = "plotVar"
PLOT_TYPE = "plotType"
PLOT_COLOR = "plotColor"
PLOT_ALPHA = "plotAlpha"
MIN_PLOT_VAL = "minPlotVal"
HAS_MIN_PLOT_VAL = "hasMinPlotVal"
MAX_PLOT_VAL = "maxPlotVal"
HAS_MAX_PLOT_VAL = "hasMaxPlotVal"
PLOT_AXIS = "axis"
PLOT_PLANE = "plane"
PLOT_X_POS = "xPos"
PLOT_Y_POS = "yPos"
PLOT_Z_POS = "zPos"
PLOT_X_POS_PREC = "xPosPrec"
PLOT_Y_POS_PREC = "yPosPrec"
PLOT_Z_POS_PREC = "zPosPrec"
FIGURE_NUM_ROWS = "numRowsInFigure"
FIGURE_NUM_COLS = "numColsInFigure"

#FILE SAVING CONSTANTS
DEFAULT_SAVE_FIGS = False
MAX_FIGURE_TITLE_CHARACTERS = 50
MAX_FILE_NAME_TIME_PREC = 10
DATA_FORMAT_VTK = "vtk"
DATA_FORMAT_MAT = "mat"
VALID_DATA_FILE_FORMATS = [DATA_FORMAT_VTK, DATA_FORMAT_MAT]
DEFAULT_DATA_FORMAT = DATA_FORMAT_MAT
MAX_OUTPUT_FOLDER_NAME_CHARACTERS = 50
MAX_OUTPUT_FILE_NAME_CHARACTERS = 50
SAVE_FIGS_DPI = "saveFigsDPI"
DEFAULT_SAVE_FIGS_DPI = 300
MIN_RECOMMENDED_SAVE_FIGS_DPI = 75
MAX_RECOMMENDED_SAVE_FIGS_DPI = 1000
IMAGE_FORMAT_PNG = "png"
IMAGE_FORMAT_PDF = "pdf"
IMAGE_FORMAT_PS = "ps"
IMAGE_FORMAT_SVGZ = "svgz"
IMAGE_FORMAT_RGBA = "rgba"
IMAGE_FORMAT_RAW = "raw"
IMAGE_FORMAT_EPS = "eps"
IMAGE_FORMAT_EMF = "emf"
DEFAULT_IMAGE_FORMAT = IMAGE_FORMAT_PNG
TIME_PRECISION_SMALL_VAL = 0.00000000000001

